spring:
  application.name: springboot-azure
  cosmos:
    uri: https://localhost:8081
    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    database: LocalDB
    max-degree-parallelism: 1
configuration:
  max-retry: 10
  initial-interval: 200
  multiplier: 2